parameters:
  directory: teste/
  vmImage: ubuntu-latest
  timeoutInMinutes: 10  # Definindo o diretório de testes

stages:
- stage: teste_unitario
  displayName: Teste Unitário
  jobs:
  - job: pytest_job
    displayName: Executando Pytest
    dependsOn: []
    timeoutInMinutes: $(parameters.timeoutInMinutes) 
    pool: 
      vmImage: $(parameters.vmImage)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10.9'
    
    - bash: |
        python -m pip install --upgrade pip
        pip install pytest
      displayName: Install dependencies
    
    - bash: |
        if [ -d "$(parameters.directory)" ]; then
          echo Pasta $(parameters.directory) encontrada executando pytest...
          python -m pytest $(parameters.directory)
        else
          echo Pasta $(parameters.directory) não encontrada, pulando teste unitario.
        fi
      displayName: Verificando existência da pasta e executando testes
    continueOnError: true 